In [17]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
raw_mail_data=pd.read_csv('mail_data.csv')

In [3]:
raw_mail_data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
mail_data=raw_mail_data.where((pd.notnull(raw_mail_data)),'')

In [5]:
mail_data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [6]:
mail_data.shape

(5572, 2)

In [7]:
mail_data.loc[mail_data['Category']=='spam','Category',]=0
mail_data.loc[mail_data['Category']=='ham','Category',]=1

In [8]:
X=mail_data['Message']
Y=mail_data['Category']

In [9]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

In [10]:
print(X.shape,'',x_train.shape,'',y_train.shape)

(5572,)  (4457,)  (4457,)

In [11]:
feature_extraction=TfidfVectorizer(min_df=1,stop_words='english',lowercase=True)
x_train_features=feature_extraction.fit_transform(x_train)
x_test_feature=feature_extraction.transform(x_test)
y_train=y_train.astype('int')
y_test=y_test.astype('int')

In [12]:
print(x_train)

5426        Oh yeah! And my diet just flew out the window
4724                     HELLO PEACH! MY CAKE TASTS LUSH!
536     Good afternoon, my love! How goes that day ? I...
3488                        Change windows logoff sound..
2551    Please sen :)my kind advice :-)please come her...
                              ...
1697    Sorry man, my stash ran dry last night and I c...
422     Someone has contacted our dating service and e...
4007    IM FINE BABES AINT BEEN UP 2 MUCH THO! SAW SCA...
3474                      You getting back any time soon?
3074           Somebody should go to andros and steal ice
Name: Message, Length: 4457, dtype: object

In [13]:
print(x_train_features)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 34895 stored elements and shape (4457, 7496)>
  Coords	Values
  (0, 4768)	0.2885879313347367
  (0, 7438)	0.2996693624522654
  (0, 2262)	0.49316930861935127
  (0, 3764)	0.22046319970004669
  (0, 2823)	0.5172500796081709
  (0, 7289)	0.5172500796081709
  (1, 3317)	0.3290434493347565
  (1, 4972)	0.49481520325330874
  (1, 1558)	0.42364007209989546
  (1, 6517)	0.49481520325330874
  (1, 4136)	0.4717788963273523
  (2, 3103)	0.17628376831968728
  (2, 841)	0.26799944639874834
  (2, 4099)	0.186263215205624
  (2, 3086)	0.27449720225122765
  (2, 2136)	0.180851695270251
  (2, 3398)	0.20665621299033204
  (2, 4269)	0.2543939099135892
  (2, 3118)	0.18009671431232455
  (2, 3935)	0.3671145612703168
  (2, 3722)	0.24768901862403342
  (2, 6641)	0.20096909705626312
  (2, 1430)	0.28509060215711635
  (2, 5837)	0.1845655907506494
  (2, 4943)	0.33789703751914013
  :	:
  (4454, 841)	0.21705430485365426
  (4454, 3514)	0.17954863693268575
  (4454, 7163)	0.15016127837290247
  (4454, 5753)	0.226337885362124
  (4454, 1150)	0.2598225428978842
  (4454, 7413)	0.2242682135068801
  (4454, 6793)	0.2084746488748568
  (4454, 7449)	0.2545599727746228
  (4454, 4477)	0.226337885362124
  (4454, 2788)	0.1933908630347447
  (4454, 5362)	0.20976307084423884
  (4454, 6656)	0.22854117433573515
  (4454, 2972)	0.2598225428978842
  (4454, 865)	0.26604684225670366
  (4454, 387)	0.2598225428978842
  (4454, 6404)	0.2834859847167938
  (4454, 4205)	0.27366476899994313
  (4454, 5765)	0.27366476899994313
  (4455, 6694)	0.4748951808522162
  (4455, 6132)	0.6072176947981236
  (4455, 3045)	0.6369939076061824
  (4456, 3484)	0.45327275707015463
  (4456, 6115)	0.4406487953685031
  (4456, 935)	0.5478925290776959
  (4456, 6279)	0.5478925290776959

In [14]:
model=LogisticRegression()

In [15]:
model.fit(x_train_features,y_train)

LogisticRegression()

In [16]:
prediction=model.predict(x_test_feature)

In [18]:
accuracy=accuracy_score(prediction,y_test)
print(accuracy)

0.9704035874439462